### ISSUE TITLE
Propose concepts from the AI Act

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#106]
The AI Act has a significant overlap with the scope of this group and work as it includes data and personal data, and has impacts to individuals. It also includes decision making, automation, and profiling - which are relevant to the DPV's concepts, as well as impact assessments that cover the same information e.g. affected rights, categories of impacts.

This issue is to track discussions regarding:

1. Whether the group should include AI Act in its scope
2. Add concepts in DPV and as an extension similar to AI Act
3. Add concepts to TECH and RISK extensions

**Comment by coolharsh55** [comment]
@delaramglp is it correct to state that we have agreed the AI Act is in scope and you will be leading the proposal based on your PhD work?

**Comment by DelaramGlp** [comment]
> @DelaramGlp is it correct to state that we have agreed the AI Act is in scope and you will be leading the proposal based on your PhD work?

Yes, it is and I would be happy to lead it.

**Comment by coolharsh55** [comment]
Great. We'll set up the spreadsheet with the terms for discussion.

**Comment by coolharsh55** [comment]
In [meeting 29 NOV](https://w3c.github.io/dpv/meetings/meeting-2023-11-29.html#t06), @DelaramGlp shared her proposal containing initial set of AI Act concepts via the [shared Google Sheet](https://docs.google.com/spreadsheets/d/17WAXH7Bkzu2m2eeOSTyhJBeHp9nst988KYCSRES8xCE/). Next step is to review these and align them with DPV. The discussion also involved the need for a new _AI extension_ (#126) which would influence the representation of these concepts.

**Comment by coolharsh55** [comment]
The AI Act extension page is live at https://w3id.org/dpv/legal/eu/aiact - currently it only has the 'System' concepts to test the output process. The namespace had to be changed from `aiact` to `eu-aiact` for consistency with e.g. `eu-gdpr`.

**Comment by coolharsh55** [comment]
Confirmed this issue can be closed in [meeting MAY-22](https://w3id.org/dpv/meetings/meeting-2024-05-22). Next steps are integration of AIRO/VAIR and discussion should continue there or a new issue should be opened for further AI Act work.
