### ISSUE TITLE
Update ODRL References to v2.2

### ISSUE THREAD

**Issue by riannella** [w3c/dpv#120]
In both the DPV and Primer final community reports, the reference to the ODRL Specification is the (old 2002) Version 1.1 W3C Note.
ODRL (in 2018) published V2.2 as a formal W3C Working Group.

Can this reference be updated to: https://www.w3.org/TR/odrl-model/

There is also the ODRL Vocabulary (that could also be referenced): https://www.w3.org/TR/odrl-vocab/

Both of these should be in the W3C ReSpec reference system

**Comment by coolharsh55** [comment]
I will update these references in the next release. Thanks for pointing it out.

**Comment by coolharsh55** [comment]
Reviewed and set to close this issue: ODRL refs point to https://www.w3.org/TR/odrl-model/

- [x] ODRL ref in DPV spec https://w3c.github.io/dpv/dpv/#bib-odrl
- [x] ODRL ref in Primer https://w3c.github.io/dpv/primer/#bib-odrl
