### ISSUE TITLE
Typo in definition of `dpv:SymmetricCryptography`

### ISSUE THREAD

**Issue by pmcb55** [w3c/dpv#122]
Typo in the `skos:definition` of `dpv:SymmetricCryptography` [here](https://github.com/w3c/dpv/blob/279acf9fe11e6e7154ae903e77a939d554b388f4/dpv/dpv.ttl#L5831), "descryption" should be "decryption":
```
dpv:SymmetricCryptography skos:inScheme <https://w3id.org/dpv#>;
    skos:definition "Use of cryptography where the same keys are utilised for encryption and descryption of information"@en;
```

Also noticed this typo too: "reprodution" should be "reproduction":
```
dpv:Copy skos:inScheme <https://w3id.org/dpv#>;
    skos:definition "to produce an exact reprodution of the data"@en;
```

**Comment by coolharsh55** [comment]
Thanks. Will fix in the next release. Will also try running a spell check to catch other similar errors.

**Comment by coolharsh55** [comment]
Implemented the changes in the spreadsheets - they will be reflected in the RDF and HTML when the documentation generator is run. 

Added to the "release checklist" I'm preparing an item to run spell check on the text. In Google Sheets, this is done by selecting the column (e.g. definition) and then Tools -> Spelling -> Spell Check. In the future, this can be integrated into the document generation pipeline, etc. by extracting text fields from CSV, running `aspell` over these, and putting the results back into the CSV. Would also help maintain a "DPV dictionary" to avoid repetitive ignoring of DPV concepts in text.

**Comment by TallTed** [comment]
Please remember that automated spellchecks do not check grammar, and thus many errors may persist — usually where an incorrect word for the context may be considered to be spelled correctly in isolation. So, proofreading by a human (or several) remains important.

**Comment by coolharsh55** [comment]
@TallTed agreed - the spellcheck is to support the human reading/reviewing the text. Personally, I tend to miss typos (and probably am responsible for most of them!).
