### ISSUE TITLE
Landing page for DPV

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#132]
A [landing page](https://en.wikipedia.org/wiki/Landing_page) for DPV would be beneficial to address the challenge where sharing the link to DPV takes the viewer straight to the technical specification which can be intimidating and verbose for a new person to figure out what DPV is, what it contains, where it can be used etc. The landing page for DPV can give this information in a easy format and then the technical specifications can be where they are. The marketing page can be what is easily shared with other people e.g. dpvcg.org and is much easier than sharing a complex w3id url or a github page. 

This issue to collect discussions regarding this in one place. 

- [DPVCG Meeting MAR-14](https://w3id.org/dpv/meetings/meeting-2024-03-13): first discussed this topic
- [DPVCG Meeting MAR-20](https://w3id.org/dpv/meetings/meeting-2024-03-20): discussed this topic - domain name, who will do the work, further discussions with example
- Update MAR-21: dpvcg.org as the domain for this

**Comment by coolharsh55** [comment]
Questions related to this:

1. Where should this landing page be? (solved --> https://dpvcg.org)
2. What content should be provided on it?
3. Where should the code/source be hosted? E.g. another branch in this repo?

**Comment by coolharsh55** [comment]
Implemented - see https://www.dpvcg.org/ source at https://github.com/coolharsh55/dpvcg.org/. Propose to move this to `dpvcg.org` branch in this repo and mirror that in another repo for the live version.

**Comment by nuthub** [comment]
I suggest to use a folder instead of a branch for the content of the landing page

**Comment by nuthub** [comment]
@coolharsh55 It's a static web page, right? What about a separate repository?

**Comment by coolharsh55** [comment]
@nuthub yes, its a static web page (now). We can have a separate repository, but this is the only "official" repo we have from w3c for all dpv stuff. So I'm thinking its good to keep to keep everything here in this repo.

**Comment by coolharsh55** [comment]
Created branch `dpvcg.org` - https://github.com/w3c/dpv/tree/dpvcg.org with website code. Will be good to set up https://github.com/coolharsh55/dpvcg.org/ to automatically mirror this branch using Github Actions in the future.
