### ISSUE TITLE
w3id update for dpv2

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#133]
Update JUN-19: w3id update needed for versioned IRIs, see https://github.com/w3c/dpv/issues/133#issuecomment-2179479007

Track https://github.com/coolharsh55/w3id.org/tree/dpv/dpv

Update MAR-18: fixed changes in [4552f92](https://github.com/coolharsh55/w3id.org/commit/4552f9221762572173b28e9f1566346478a5fb31) and submitted as PR to perma-id/w3id.org#3969

Update MAR-18: The previous commit [819af4c](https://github.com/coolharsh55/w3id.org/commit/819af4c5530be88bbf5f04505c61011dceffa596) was submitted as the PR perma-id/w3id.org#3958, which was merged. However, older w3ids are broken e.g. dpv-pd returns 404.

Fix is to explicitly redirect them to the newer ones (see table in the README) - I'll get to this in the morning. 

Self note: for future fixes `curl -IL <URL> | grep "HTTP\|location"` will give the HTTP status code and final url (if it exists). Put this in a script that takes the w3id links table and checks all urls resolve as expected.

**Comment by coolharsh55** [comment]
1. Fixed issues related to broken purls (dpv-owl etc.) in [6147934](https://github.com/coolharsh55/w3id.org/commit/6147934ce10880ed1396e2769045725e61fd1e34) and created perma-id/w3id.org#4027
2. Fixed issues related to /owl suffix not resolving to correct address in [7202002](https://github.com/coolharsh55/w3id.org/commit/72020028df0b78aa74e2878346ed743d85bfe864) and created perma-id/w3id.org#4031

**Comment by coolharsh55** [comment]
HTML links work as expected - check RDF and OWL links work as well and close the issue.

**Comment by coolharsh55** [comment]
w3id update needed for versioned IRIs where the paths are now `w3id.org/dpv/v1.0` and `w3id.org/dpv/v2.0` instead of `w3id.org/dpv`

**Comment by besteves4** [comment]
@coolharsh55  Does this work as an approach to be followed by the extensions as well?
```
|--------------------+------------------------------------------+-------------------------------------------------------------+-----------------------------------------------------------------|
| prefix             | w3id                                     | HTML                                                        | RDF                                                             |
|--------------------+------------------------------------------+-------------------------------------------------------------+-----------------------------------------------------------------|
| dpv                | https://w3id.org/dpv                     | https://w3c.github.io/dpv/v2.0/dpv                          | https://w3c.github.io/dpv/v2.0/dpv/dpv.rdf                      |
| dpv-owl            | https://w3id.org/dpv/owl                 | https://w3c.github.io/dpv/v2.0/dpv/dpv-owl.html             | https://w3c.github.io/dpv/v2.0/dpv/dpv-owl.rdf                  |
| dpv-v1             | https://w3id.org/dpv/v1.0                | https://w3c.github.io/dpv/v1.0/dpv                          | https://w3c.github.io/dpv/v1.0/dpv/dpv.rdf                      |
| dpv-owl-v1         | https://w3id.org/dpv/owl/v1.0            | https://w3c.github.io/dpv/v1.0/dpv-owl                      | https://w3c.github.io/dpv/v1.0/dpv-owl/dpv.rdf                  |
| dpv-v2             | https://w3id.org/dpv/v2.0                | https://w3c.github.io/dpv/v2.0/dpv                          | https://w3c.github.io/dpv/v2.0/dpv/dpv.rdf                      |
| dpv-owl-v2         | https://w3id.org/dpv/owl/v2.0            | https://w3c.github.io/dpv/v2.0/dpv/dpv-owl.html             | https://w3c.github.io/dpv/v2.0/dpv/dpv-owl.rdf                  |
```

**Comment by coolharsh55** [comment]
Hi. We don't need versioned prefixes - they will get out of hand quickly. The prefix shouldn't change IMHO - only the IRI should. E.g. DCAT v2 and v3 still use the same `dcat` prefix for both. 

The IRIs following the same style e.g. `v2.0/owl` and `v1.0/owl` do make sense, but in any case we would have to support the earlier IRIs and redirect them e.g. `dpv-owl` -> `v1.0/owl`. In the `v1.0` folder, I just prefixed the version in the IRI as `v1.0/dpv-owl`, so I'd need to change the IRIs in v1.0 to have that structure if we go ahead with this format.

**Comment by coolharsh55** [comment]
And I just now realised that DCAT v2 and v3 have the SAME IRI - `http://www.w3.org/ns/dcat#` as the two versions are deemed 'compatible' (see [v2](https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat2.ttl) and [v3](https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat3.ttl) and w3c/dxwg#1128 for the discussion)

**Comment by coolharsh55** [comment]
@besteves4 see discussion https://github.com/w3c/dpv/issues/45#issuecomment-2184828519 for naming the IRI and folder as `2.0` instead of `v2.0` (I've already made the changes in repo `dev` branch)

**Comment by besteves4** [comment]
@coolharsh55 I'm still seeing `@prefix dpv: <https://w3id.org/dpv/v1.0#> .` in the v1 `dpv-gdpr.ttl`, the correct namespace should be `<https://w3id.org/dpv/1.0#> .` right?

**Comment by coolharsh55** [comment]
You're correct - it should have been `1.0`. I replaced the IRI (search+replace with good old sed) - so that should be correct now.

**Comment by besteves4** [comment]
I don't see any references to `dpv-nace` in the w3id configuration, nothing to do there for the new versioned config?

**Comment by coolharsh55** [comment]
No, we deprecate dpv-nace for two reasons: 1) I don't see anyone using it; and 2) EU already publishes NACE with authoritative IRIs and they have an update to NACE as v2.1 whereas our stuff is v2. People using NACE should use the official IRIs.

**Comment by besteves4** [comment]
@coolharsh55 changes done in https://github.com/besteves4/w3id.org/commit/89ff83417a6b9c13bae46b02e91f30fd06eea5a3, it would be nice if you could review it before I make the PR.

**Comment by coolharsh55** [comment]
@besteves4 hi, thanks, looks good - a few minor things for which I have left comments on your commit

**Comment by besteves4** [comment]
suggested changes in https://github.com/besteves4/w3id.org/commit/9e9a64f7941081e3ad3f6a5b768401569ce0f2b7, if ok I'll open the PR to the [perma-id](https://github.com/perma-id/w3id.org) repo

**Comment by coolharsh55** [comment]
@besteves4 yes I think looks okay for a PR (you can check with `apachectl configtest` if you have apache)

**Comment by besteves4** [comment]
great, made the PR [here](https://github.com/perma-id/w3id.org/pull/4218)

**Comment by besteves4** [comment]
PR merged, it would be good to check that everything is running smoothly!

**Comment by coolharsh55** [comment]
Shall I move/merge `dev` into `main` and then we check?

**Comment by coolharsh55** [comment]
Links work as expected.
