### ISSUE TITLE
Changing tech:TechnologyActor to tech:Actor

### ISSUE THREAD

**Issue by DelaramGlp** [w3c/dpv#142]
I propose removing Technology from ``tech:TechnologyActor``  and all its subclasses, as it seems redundant. When it is in the tech extension then there is no need to repeat Technology and we can simply call it ``tech:Actor``.

**Comment by coolharsh55** [comment]
Okay with me. Though - would the definition then state technology e.g. Provider is the actor that provides technology? Because Provider also applies to non-technology contexts e.g. service provider, data provider, healthcare provider.

**Comment by DelaramGlp** [comment]
Yes, the definition should have technology in it.

**Comment by coolharsh55** [comment]
Okay, I'll modify the terms and add it in the revision to tech extension. TBD in next meeting. I won't be attending - but I'll put this on the agenda.

**Comment by coolharsh55** [comment]
@DelaramGlp see https://harshp.com/dpv/tech/ (see the taxonomy and ignore the errors and outdated text). Is this what you require? Or is something missing?

**Comment by DelaramGlp** [comment]
Looks good to me and covers what I need for now. Thanks!
