### ISSUE TITLE
Notes on Primer - Sections 1 through 3

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [w3c/dpv#150]
1. In Example 1, the term 'subtype' is used in the sentence "To specifically refer to 'email address', the concept Email Address should be used, which is a 'subtype' of Email". The relationship between 'Email Address' and 'Email' is one of aggregation. 'Email' hasA 'Email Address'; 'Email Address' isA 'Email' does not make sense. Even if there is a valid context for the use of 'subtype' to describe concepts that are aggregated into another concept, most programmers will think 'isA' when they read 'subtype'. Further, the table in section 3.2 states that 'is subtype of' maps to rdfs:subClassOf, which embodies 'isA', not aggregation.
2. The first phrase of the first sentence of the first paragraph of section 3.2 makes no sense: "Where the [[DPV](https://w3c.github.io/dpv/primer/#bib-dpv)] specification defines concepts and relationships between them as 'terms' intended to represent them as 'concepts'"
3. The second paragraph of section 3.2 contains the following non sentence: "For example, specifying that the relation 'has personal data' must always be associated with 'Personal Data'." You may need to rewrite the entire second paragraph.
4. In Example 2, in the OWL2 Modeling section, you list problems and solutions. Assume I’m a RDF / OWL / SKOS n00b - I don’t know what you’re trying to say here. It isn’t clear if statements like ‘ex:CampaignB a ex:CampaignA .’ are valid or not. Please be more explicit.

**Comment by coolharsh55** [comment]
Thanks for the review Steve. Can you please use one issue e.g. this for the review so as to avoid having too many of them to go through? You can add comments for new findings.

**Comment by coolharsh55** [comment]
Made changes, see live version at: https://www.w3id.org/dpv/primer

**Comment by TallTed** [comment]
https://github.com/w3c/dpv/commit/9ccf3e4dddb74f68f73f252bd38c84fe5f246377 should have been a PR.

* Note that `(e.g. 'is-a'` should be `(e.g., 'is-a'` — note the comma.

* Note that `'directly' e.g. an use-case` should be `'directly', e.g., a use-case` — note the commas and the `an`→`a`.

* There are many other instances of `e.g.` (and of its cousin, `i.e.`) which either require some additional commas or other punctuation, or would be better replaced by words along with some minor rephrasing of the existing words around them.

* `organisations` and other `en-uk` spellings should be replaced by `organizations` and their `en-us` spellings (as this is a [W3C document](https://www.w3.org/Guide/manual-of-style/#Spelling))

There would be a large number of other comments, but this is a horrible way to communicate such. There should be a map *somewhere* (maybe in the [README](https://github.com/w3c/dpv/blob/master/README.md)?) that indicates the *source documents* which should be reviewed for content (as opposed to the *artifact documents* which are produced by processes acting on the source documents and which should not be reviewed directly).

**Comment by coolharsh55** [comment]
I don't know what you mean by source - if you are reviewing the HTML then that is correct. If you want to change the way the HTML is generated, then you need to look at the source document or script or template. What you are suggesting should be reviewed in the HTML outputs. What you call as artefact documents should be the one for reviewing as the source documents can be python scripts or jinja2 templates which not everyone can understand. If you want to implement them e.g. in a PR, let me know and I'll help with how to do it.

Your suggested changes are purely editorial - so we will implement them as time permits but they are not a priority. Except for language - we are using UK english. There is no requirement for using US english - the guideline you have is for W3C technical reports which is not what this work is. Besides, its a guideline and we have consistenly used UK english so far, so it would not be good to change it now.
