### ISSUE TITLE
Primer Section 4.2, subsection on Data and Personal Data - clarification needed

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [w3c/dpv#151]
That section states:
“DPV defines the concept Data which has subtypes NonPersonalData and PersonalData, which are associated using the relation hasData. To specifically indicate involvement of personal data, DPV provides the relation hasPersonalData.” Figure 4 does not include the relation ‘hasData’. If this is an oversight, then update the diagram. If this is deliberate, then tell the reader that Figure 4 is incomplete (and why it is incomplete). If the relation ‘hasData’ no longer exists, then correct this paragraph.

**Comment by coolharsh55** [comment]
Thanks Steve. The figure needs to be updated in this case - all figures in all documents need to be updated.

**Comment by TallTed** [comment]
> @[coolharsh55](https://github.com/coolharsh55) coolharsh55 closed this as [completed](https://github.com/w3c/dpv/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [7 hours ago](https://github.com/w3c/dpv/issues/151#event-13215395260)

...but there's no indication of where/how to review that "completion" and confirm that it did indeed complete a fix.

**Comment by coolharsh55** [comment]
This was discussed in the meeting with Steve and closed after that.
