### ISSUE TITLE
Primer Section 4.2 subsection Entities

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [w3c/dpv#152]
Figure 10 indicates that Representative, DataController, DataProcessor, ThirdParty, Authority, and DataSubject all have a 'isSubTypeOf' relation with LegalEntity.

I don't know if that is consistent with the rest of DPV or not, but I do know that these are all roles that the same LegalEntity can play at different times. And sometimes the same LegalEntity can play more than one of these roles in the same context. For example:

My optometrist also sells glasses. If he or one of his family needs glasses, then he will buy them from his own store. In that transaction, he is the DataSubject and the DataController at the same time.

I do not think 'isSubTypeOf' is the appropriate relation between these concepts.

**Comment by coolharsh55** [comment]
Hi. The figure needs to be updated here. 'subtype' or 'subclass' is the correct relation here, as both controller and data subject are 'legal entities'. The relationship is not between controller and data subject.

**Comment by steve-hickman-epistimis** [comment]
I may not have properly communicated my concern.  I was not trying to say that there was any relationship between controller and data subject. What I was trying to point out is that the same LegalEntity can play the role of a controller and a data subject - and sometimes can do so at the same time. By making DataSubject and DataController subclasses of LegalEntity that that an instance of LegalEntity can be both an instance of DataSubject and an instance of DataController at the same time.  Is that your intent?

**Comment by coolharsh55** [comment]
No, not my 'intent', but it isn't prohibited in DPV or in GDPR. E.g. see "[Data subjects as data controllers: a Fashion(able) concept?](https://policyreview.info/articles/news/data-subjects-data-controllers-fashionable-concept/1400)" Conversely, what this permits is data Controller in one use-case can be the data subject in another (so they are both controller and data subject in a combined graph). So I think its correct (modelling).
