### ISSUE TITLE
Primer Section 4 organization does not match Section 5 organization

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [w3c/dpv#153]
Primer Section 4.2  Overview of Core Concepts is not in the same order as Section 5.  

Section 4.2 ordering:

- Data and Personal Data
- Purpose
- Processing
- Processing and Storage Conditions
- Legal Basis
- Entities
- Data Controller
- DataSubject
- Recipient
- Technical Organisational Measure
- Rights
- Risk
- Technology
- Location and Jurisdiction
- Rules

Section 5 ordering:

- Purpose
- Processing Operations
- Data & Personal Data
- Technical and Organisational Measures
- Legal Basis
- Entities
- Location and Jurisdiction
- Contextual Information
- Risk Assessment
- Rights and Rights Exercise
- Rules
- 

It would be helpful if these were in the same order. Readers would be able to check their reading progress more easily.

**Comment by coolharsh55** [comment]
Agree, will change the order. Thanks.

**Comment by coolharsh55** [comment]
Made changes, see live version at: https://www.w3id.org/dpv/primer
