### ISSUE TITLE
Primer Section 4.3 Process and PersonalDataHandling

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [w3c/dpv#154]
Section 4.3 has a NOTE box indicating that DPV v2 uses Process to replace DPV v1 PersonalDataHandling.  The content of that note states that Process replaces Process. It looks like someone did a global find and replace 'PersonalDataHandling' -> 'Process' after inserting this NOTE instead of before inserting it.  There may be other places where this resulted in 'Process' where 'PersonalDataHandling' should have remained.

Also: There appear to be places (see Example 7) where 'Personal Data Handling' (with embedded spaces) remains where you may have intended to say 'Process'

**Comment by coolharsh55** [comment]
Thanks, I'll check and correct the two terms in the document.

**Comment by coolharsh55** [comment]
Made changes, see live version at: https://www.w3id.org/dpv/primer
