### ISSUE TITLE
Primer section 4.3 subsection Alternative Models

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [w3c/dpv#155]
Second paragraph contains the sentence:
"For example, instead of expressing the relationship between personal data and purpose through a Process instance, an alternate model could be one where the purpose directly specifies what personal data it uses as: <SomePurpose hasPersonalData SomePersonalData>."

I do not see how a purpose can be directly related to specific data.  If this is possible, please provide more details for your example. If not, please find a different example. If Example 8 provides the intended detail, then reference it in the above sentence so that the reader knows to look further down for that detail - or move Example 8 up before this sentence so that the reader will already be familiar with the example before you state the claim made in this sentence.

The next sentence is: 
"Similarly, another instance for such alternate use of concepts is to associate a legal basis directly with the purpose by using the hasLegalBasis relationship."

I do not understand this statement. What two things does 'hasLegalBasis' relate?  Figure 19 shows that relationship between PersonalData and LegalBasis. It does not show this relationship involving Purpose.

This entire section is written in a way that seems to indicate using Purpose to relate personal data and processing is OK - only to say at the end of paragraph 3 that this approach is not recommended. If an approach is not recommended, state that before describing it to help the reader create the appropriate mindset. You can explain *why* it's not recommended after you explain what it is - but tell them it isn't recommended up front.

**Comment by coolharsh55** [comment]
Thanks. I will move the caution to earlier in that section, and give an example of what using purposes in this way would be.

**Comment by coolharsh55** [comment]
Made changes, see live version at: https://www.w3id.org/dpv/primer
