### ISSUE TITLE
Link to v2 changelog is broken

### ISSUE THREAD

**Issue by jeswr** [w3c/dpv#157]
The link to the v2 changelog referenced [here](https://github.com/w3c/dpv/blob/040e40429ccd249dc88822292d29c933c47ab8f9/README.md?plain=1#L8) is broken.

**Comment by coolharsh55** [comment]
Drats. Thanks for the issue. I'll put it up over the weekend.

**Comment by jeswr** [comment]
Ta - follow up question, is the namespace of DPV v2 the same as DPV v1 (I was trying to look at the changelog to answer this question in the first place).

**Comment by coolharsh55** [comment]
Hi Jesse. Yes, (for now) the namespace is the same. Though we are discussing how to also create separate namespaces for cases where someone wants to continue using a previous version (e.g. `w3id.org/dpv/v2`). If you have ideas or preferences or suggestions - please let us know. We discussed this in the last meeting, and there will be an issue on this soon as I get to publish the minutes.

**Comment by coolharsh55** [comment]
Okay, we have kickstarted the process to do versioned IRIs - see #45 or the [mailing list](https://lists.w3.org/Archives/Public/public-dpvcg/2024Jun/0001.html). @jeswr would be great to have your thoughts/support here.

**Comment by coolharsh55** [comment]
@jeswr hi - apologies for the delay on this, the changelog is on the dev branch and we are waiting to confirm its okay to make the changes to main branch for the new repo structure. The dev changelog is live and the link will redirect to https://dev.dpvcg.org/v2.0/changelog until then.

**Comment by coolharsh55** [comment]
There's an error in the changelog where the v1.0 IRI is incorrectly stated as v2.0

> DPV v2.0 introduces versioned IRIs e.g. https://w3id.org/dpv/v2.0 refers to v2.0 and [https://w3id.org/dpv/**v2.0**](https://w3id.org/dpv/v1.0) refers to v1.0.

**Comment by coolharsh55** [comment]
The link to the dev changelog has changed as we moved from `v2.0` to `2.0` in version naming. The link is: https://dev.dpvcg.org/2.0/changelog
