### ISSUE TITLE
CSV/JSON output of DPV v2 and extensions

### ISSUE THREAD

**Issue by thovden** [w3c/dpv#165]
In addition to the existing outputs, provide a simplified output of DPV terms in CSV and/or JSON format to enable easier integration for applications that do not need the full semantics of the DPV. 

For the CSV, a format could be exported directly from the Google Spreadsheets, e.g., : https://docs.google.com/spreadsheets/d/1SI6gZh9-dq1rf_etfrlYHj0QZwq9Vd25f_OHPX5hbSQ/gviz/tq?tqx=out:csv&sheet=1VPQW1DanprQhMwnhSqyKSGbEXdTmLHdc6UjpWJhyLMA&headers=1

**Comment by thovden** [comment]
It would go great to have the .csv files output alongside the other exports, e.g., 

```
v2/
     ai/
         ai.csv
         ai.jsonld
         [...]
```

The rows in the CSV should be named with the same names as used elsewhere in the DPV - e.g., `term`,`label`, `isSubclassOf` and so on.

**Comment by coolharsh55** [comment]
@thovden please see CSV files - where:
  - term is the DPV term without vocab namespace e.g. AcademicResearch
  - type represents if it is a rdfs:Class or rdf:Property
  - dpvtype is the DPV term whose instance the term is e.g. Purpose
  - subclassof indicates the DPV term that is used with rdfs:subClasOf
  - hasbroader lists the DPV terms used with skos:broader
  - vocab provides the vocab identifier e.g. dpv
  - namespace provides the vocab IRI e.g. https://w3id.org/dpv
  - iri = namespace + term

| **term**         | **type** | **iri**                               | **label**         | **definition**                                                                                                                  | **dpvtype**                                | **subclassof**                              | **hasbroader** | **scopenote** | **created**          | **modified** | **vocab** | **namespace** |
|------------------|----------|---------------------------------------|-------------------|---------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------|---------------------------------------------|----------------|---------------|----------------------|--------------|-----------|---------------|
| AILiteracy       | class    | https://w3id.org/dpv#AILiteracy       | AI Literacy       | Providing skills, knowledge, and understanding to enable reading, writing, analysing, reasoning, and communicating regarding AI | https://w3id.org/dpv#OrganisationalMeasure | https://w3id.org/dpv#DigitalLiteracy        | 2024-05-17     | dpv           | https://w3id.org/dpv |              |           |               |
| AcademicResearch | class    | https://w3id.org/dpv#AcademicResearch | Academic Research | Purposes associated with conducting or assisting with research conducted in an academic context e.g. within universities        | https://w3id.org/dpv#Purpose               | https://w3id.org/dpv#ResearchAndDevelopment | 2019-04-05     | dpv           | https://w3id.org/dpv |              |           |               |

**Comment by coolharsh55** [comment]
Hi. The files are in the `dev` branch under v1.0 and v2.0. CSV files are only provided for v2.0 https://github.com/w3c/dpv/tree/dev and the live version is at dev.dpvcg.org e.g. https://dev.dpvcg.org/v2.0/dpv/

**Comment by thovden** [comment]
@coolharsh55  thanks - I'll have a go at integrating this tomorrow. I'll leave feedback here if any.

**Comment by TallTed** [comment]
> [@coolharsh55] @thovden please see CSV files - where:

I've edited the following, to better present the info —

> * **`term`** is the DPV term without `vocab` namespace, e.g., `AcademicResearch`
> * **`type`** represents whether it is an `rdfs:Class` or `rdf:Property`
> * **`dpvtype`** is the DPV term whose instance the term is, e.g., `Purpose`
> * **`subclassof`** indicates the DPV term that is used with `rdfs:subClasOf`
> * **`hasbroader`** lists the DPV terms used with `skos:broader`
> * **`vocab`** provides the vocab identifier, e.g., `dpv`
> * **`namespace`** provides the `vocab` IRI, e.g., `https://w3id.org/dpv/#`
> * **`iri`** = `namespace` + `term`, e.g., `https://w3id.org/dpv/#AcademicResearch`

(First off, *either* `namespace` above must be changed as I have, i.e., `https://w3id.org/dpv` must become `https://w3id.org/dpv/#`, *or* `iri` above must change to ``` `namespace` + `/#` + `term` ```. And, if all this data *is* being managed in GSheets, all those descriptions should be incorporated in that worksheet, either as cell comments *or* (probably better) as a new column.)

I can't imagine that there are many humans who find CSV files useful for manual review. *Usually*, CSV files are used for data transfer, and loaded/exported to/from applications that offer tabular editing interfaces, similar to what you have [presented here](https://github.com/w3c/dpv/issues/165#issuecomment-2171818960).

GitHub is a terrible place in which to manage data. It's simply not designed for it. Changes, suggestions, etc., *do* need to be tracked, and credit/blame extended to the relevant authors, editors, etc. Google Spreadsheets *might* be the best option, today, though it will mean that extra effort needs to be applied by the spreadsheet owner, to map Google User IDs to GitHub Handles, among other things (such as documenting import/export procedures, such that all editors execute the same steps and don't break each other's efforts — which is difficult to prevent, unless all editors are working on the same worksheet instance, and doing that work *within* GSheets)....

**Comment by coolharsh55** [comment]
@TallTed this is the output CSVs being produced as another format/serialisation alongside RDF and HTML. The first comment in the issue clearly states this. Google sheets spreadsheets are where we do discussions on new concepts and changes - that is not linked to this work at all so nothing needs to be mentioned/put there from this issue.

**Comment by thovden** [comment]
For IRIs and namespaces - will the exported RDF, CSV and so on have the specific versioned IRIs - e.g., `https://w3id.org/dpv/v2.0/ai#AI` or the unversioned one `https://w3id.org/dpv/ai#AI` or both? If the definitions and/or semantics change across versions we need to track which version of a term is in use in our application. 

Also see https://github.com/w3c/dpv/issues/45

**Comment by coolharsh55** [comment]
> For IRIs and namespaces - will the exported RDF, CSV and so on have the specific versioned IRIs - e.g., `https://w3id.org/dpv/v2.0/ai#AI` or the unversioned one `https://w3id.org/dpv/ai#AI` or both? If the definitions and/or semantics change across versions we need to track which version of a term is in use in our application.

It will contain the versioned IRIs e.g. `https://www.w3id.org/dpv/v2.0/ai#AI`

**Comment by thovden** [comment]
@coolharsh55 looking good for the most part on my side. However, the `legal-eu` vocab is empty in the CSV file, and e.g., the adequacy decision are not there. They are exported into the other formats.

**Comment by coolharsh55** [comment]
@thovden this should be fixed now - please see https://github.com/w3c/dpv/blob/dev/v2.0/legal/legal.csv

**Comment by coolharsh55** [comment]
@thovden thanks for spotting that (mea culpa) - I think it should be fixed now with the commit. `legal.csv` and `legal-eu.csv` have data as expected, and `legal.csv` uses the correct vocab and namespace. Copied over sample outputs from `legal.csv`:

term | type | iri | vocab | namespace
-- | -- | -- | -- | --
law-TH-ThürDSG | class | https://w3id.org/dpv/v2.0/legal/de#law-TH-ThürDSG | legal-de | https://w3id.org/dpv/v2.0/legal/de
Adequacy-EU-AD | class | https://w3id.org/dpv/v2.0/legal/eu#Adequacy-EU-AD | legal-eu | https://w3id.org/dpv/v2.0/legal/eu

Also checked for regression: [dpv.csv](https://github.com/w3c/dpv/blob/dev/v2.0/dpv/dpv.csv),  [pd.csv](https://github.com/w3c/dpv/blob/dev/v2.0/pd/pd.csv), and [eu-gdpr.csv](https://github.com/w3c/dpv/blob/dev/v2.0/legal/eu/gdpr/eu-gdpr.csv) have correct data.

**Comment by coolharsh55** [comment]
@thovden we had to change the IRI (again) as our implementation was not according to best practice. We removed versioned IRIs e.g. `https://w3id.org/dpv/2.0#Purpose` and replaced it with the versionless IRIs e.g. `https://w3id.org/dpv#Purpose`. Please review the CSV.

The term IRIs will not change across different versions. The entire ontology/file will be available at the versioned IRIs e.g. `https://w3id.org/dpv/2.0` will give DPV v2 with terms using the versionless IRI.

**Comment by coolharsh55** [comment]
Confirmed via DM/emails the CSV outputs are okay. Closing issue as completed.
