### ISSUE TITLE
[FIX]: issues on the PD extension

### ISSUE THREAD

**Issue by besteves4** [w3c/dpv#176]
### Specs

Personal Data (PD)

### Errors

A couple of fixes for the final v2 release:
- Duplicated birth place concepts: there's [https://w3id.org/dpv/pd#BirthPlace](https://w3c.github.io/dpv/2.0/pd/#BirthPlace) and [https://w3id.org/dpv/pd#PlaceOfBirth](https://w3c.github.io/dpv/2.0/pd/#PlaceOfBirth)
- A few location-related concepts are being defined as narrower than `dpv:Location` instead of `pd:Location`, i.e., `pd:Residency` and `pd: Domicile`
- Similarly, `pd:CountryOfBirth` is under `dpv:Country` instead of `pd:Country`

Also, for a future release:
- Figure 1 does not have `pd:Profile` as a top concept
- Section 2 (Extended Taxonomy) does not have subsections for Profile or Household

**Comment by coolharsh55** [comment]
@besteves4 made changes, see live version at: https://dev.dpvcg.org/2.1-dev/pd/. Since we haven't added `2.1-dev` to w3id, the usual redirects won't work until we do that. I'm fine with using dev.dpvcg.org for the moment if that isn't inconvenient.

**Comment by besteves4** [comment]
That works. Maybe we should have an issue tracking the w3id's we need for `2.1-dev` and I can add them after the final v2.0 release.
