### ISSUE TITLE
[FIX]: Hyper link incorrect 

### ISSUE THREAD

**Issue by Paul-Ryan76** [w3c/dpv#188]
### Specs

DPV

### Errors

Fix ...https://w3c.github.io/dpv/guides/gdpr-ropa ... this link is going to data breach page

**Comment by coolharsh55** [comment]
Applied the fix in https://github.com/w3c/dpv/commit/6acbf2ba00431df58c2ac9abb2ae62c907c9eb7e. This commit will be closed automatically when `dev` is merged into `master`.
