### ISSUE TITLE
[Concept]:  Technically specifying PII Principal and Data Subject for Authorisation with Consent: Introducing the Master Data Controller Term

### ISSUE THREAD

**Issue by smartopian** [w3c/dpv#193]
Withdrawn - no source

**Comment by coolharsh55** [comment]
Hi. What is the source for this new term "_Master Data Controller_" you are proposing? We already have Data Controller - what is the meaning of prefixing it with "_Master_"? The given definition is confusing for me, e.g. "both the PII Principal and Data Subject" - where PII Principal and Data Subject mean the same things in ISO and GDPR respectively. 

Also, the given usage note does not provide any clarity, e.g. "technically address delegation of authority addressing technical requirements for all privacy stakeholders" - I have no idea what this implies. The next statements also do not provide any clarity - what are notice receipts? What does it mean to "assert themselves as Master Data controller"?

Please provide a clear and well-defined justification for why the new term is to be added and how it relates to existing well established terms. The given source is not sufficient - I cannot find anything related to this from looking at this work from 2005.
