### ISSUE TITLE
Formulate a notion of compliance in the scope of the CG

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#2]
| Migrated [ISSUE-2](https://www.w3.org/community/dpvcg/track/issues/2) Do we need to formulate a notion of compliance in scope of the cg?

State: RAISED
Opened on: 2018-09-18
Related emails:

1.  +[\[minutes\] 2019-10-15 dpvcg](https://www.w3.org/mid/20191015183654.9D243961A00@nyx.sophia.w3.org) (from bert@w3.org on 2019-10-15)
2.  +[ACTION-97 (was: ACTION-89)](https://www.w3.org/mid/55659E1B-6A34-436D-9EC9-9D07E139A798@wu.ac.at) (from axel.polleres@wu.ac.at on 2019-04-22)
3.  +[\[minutes\] 2018-09-18 dpvcg](https://www.w3.org/mid/20180919161934.299AE961A3C@nyx.sophia.w3.org) (from bert@w3.org on 2018-09-19)
4.  +[ISSUE-2: Do we need to formulate a notion of compliance in scope of the cg?](https://www.w3.org/mid/E1g2HM6-0002sj-Vu@asterion.w3.org) (from sysbot+tracker@w3.org on 2018-09-18)

Notes:

RESOLVED: move issue-2 to postponed issues under the following text: "The group did not concsider defining any notion of (legal) compliance with respect to a particular legislation in scope of the current specification. While we assume that certain violations of compliance could be recorded with the current vocabulary, compliance guarantees or compliance checking algorithms are not part of this specification."
Axel Polleres, 15 Oct 2019, 14:26:54

**Comment by coolharsh55** [comment]
Marking this as complete as we have `dpv:ComplianceStatus`, `dpv:Lawfulness`, and `eu-gdpr:GDPRLawfulness`. For further discussion on representing more detailed compliance information e.g. which article, degree of compliance, method of compliance evaluation - a separate discussion and issue should be used.

**Comment by besteves4** [comment]
would it then make sense to have these `eu-gdpr:GDPRLawfulness` for the other legal extensions we already have?
