### ISSUE TITLE
use `rdfs:seeAlso` instead of `rdfs:isDefinedBy` to link background information.

### ISSUE THREAD

**Issue by rpietzsch** [w3c/dpv#28]
I'd like to suggest to adopt the best practice of using `rdfs:isDefinedBy` _to indicate an RDF vocabulary in which a resource is described_ (https://www.w3.org/TR/rdf-schema/#ch_isdefinedby) and `rdfs:seeAlso` to provide the article context.

**Comment by coolharsh55** [comment]
Hi. The RDFS documentation for `rdfs:isDefinedBy` further notes:

> It may be possible to retrieve representations of O from the Web, but this is not required. When such representations may be retrieved, no constraints are placed on the format of those representations. rdfs:isDefinedBy is a subproperty of rdfs:seeAlso.
The rdfs:domain of rdfs:isDefinedBy is rdfs:Resource. The rdfs:range of rdfs:isDefinedBy is rdfs:Resource.

It is cumbersome and IMHO unnecessary to represent EVERYTHING in RDF just so it can be used as an `rdfs:Resource`. Most of the things defined in DPV have origins in documents and reports that are not in RDF. Given that the `rdfs:range` for this propery is `rdfs:Resource`, anything used with `rdfs:isDefinedBy` can be inferred to be a resource if strict semantics are necessary. For example, `<some-DPV-concept> rdfs:isDefinedBy <some-random-url>` is indicative of `<some-random-url>` being a `rdfs:Resource`.

**Comment by rpietzsch** [comment]
Hi, I understand your argument and am fully in line with your argumentation. I was not arguing for `rdfs:Resource`; I basically tried to suggest to use `rdfs:seeAlso` in place of your current use of `rdfs:isDefinedBy`. E.g.:

```ttl
dpv-gdpr:A13 a rdfs:Class ;
    # ...
    rdfs:seeAlso <https://eur-lex.europa.eu/eli/reg/2016/679/art_13/oj> ;
    rdfs:isDefinedBy dpv-gdpr: ;
    # ... 
.
```

**Comment by coolharsh55** [comment]
Hi. DPV v0.4 now uses `rdfs:isDefinedBy` to declare the concepts are present in (that) vocabulary, and `dct:source` to indicate the origin/source of that concept. If there are no further discussions on this, I will close the issue next week.

**Comment by seebi** [comment]
thanks
