### ISSUE TITLE
Personal data category semantics

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dpv#35]
Hi,

I have troubles to understand the Personal data categories as classes
For example:
> 
> https://w3c.github.io/dpv/dpv-pd/#CarOwned: Information about cars ownership and ownership history.
> 

How should this be used?

```
_:agent1 dpv-pd:CarOwned  [
     ex:licenceplate "231321-31213-31231"; 
     ex:model "ferrari"
].
```

But that conflicts with the statement it is a class, because it is used as a property.

Or is this intented to be used as RDFstar?
```
<< _:agent1 ex:buys  [
     ex:licenceplate "231321-31213-31231"; 
     ex:model "ferrari"
]. >> a dpv-db:CarOwned
````

This is all very fuzzy to me.

Secondly I wonder why this list even exists at all. Any agent property is valid isn't it? This looks like an attempt to model the world. For instance this repository contains many personal data information data models: https://github.com/SEMICeu/SDG-sandbox/tree/master/evidences
How can they be integrated in the approach? 
Or some further away datamodels like https://smartdatamodels.org/?

How is this envisioned?

kr,

Bert

**Comment by coolharsh55** [comment]
@bertvannuffelen Hi, are there any follow-up discussions on this issue? Otherwise, may we close it?

**Comment by bertvannuffelen** [comment]
@coolharsh55 I understand the scope now of the DPV-PD. 

But I think I see in you examples what my issue is: the subject `_:agent1` has disappeared in your rewording of the example.
How is that link maintained?

**Comment by coolharsh55** [comment]
Hi. Do you mean the association of personal data with an entity/agent? Is it something like this:

```
ex:Agent dpv:hasPersonalData dpv-pd:CarOwned .
```

To avoid associating the entire category with that data subject / agent, this might be a better representation:
```
ex:GoldfingerBondCar a dpv-pd:CarOwned ;
   dct:title "Bond's Car in Goldfinger 1964"@en ;
   car:model "Aston Martin DB5" .
   # external vocabulary to describe domain knowledge 
   # Or create more subtypes from CarOwned 
   # e.g. Car Model skos:broader / rdfs:subClassOf Car Owned
ex:Bond007 a dpv:DataSubject ;
   dpv:hasPersonalData ex:GoldfingerBondCar .  # only this person's car

**Comment by coolharsh55** [comment]
I think there's some misunderstanding (not sure if on your part or mine). There are no expansions for a triple `< :s :p :o >`. So your expression is actually two sets of triples - first asserting `<a>` is a data subject, and the second specifying they have personal data `:apd`.
```
<a> a dpv:DataSubject; 
    dpv:hasPersonalData _:apd.
```

DPV doesn't mandate only using the core model, which is also why properties have range but no domains. So you can use `hasPersonalData` in several contexts, e.g.
```
# to represent processing operations
ex:A a dpv:PersonalDataHandling ;
    dpv:hasPersonalData dpv-pd:Email .

# to represent an individual's data
ex:B a dpv:DataSubject ;
    dpv:hasPersonalData "hello@example.com" .

# to represent a privacy notice specifies personal data
ex:C a dpv:PrivacyNotice ;
    dpv:hasPersonalData dpv-pd:Email .
```
Does this clarify the use?

**Comment by coolharsh55** [comment]
Hi @bertvannuffelen is there anything to add for this issue? IF not, it will be resolved as part of the cleanup after November-15. Please let me know if this issue should be left open instead. Thanks.

**Comment by bertvannuffelen** [comment]
The only thing to add is that the diagram in Figure 1 is indicating an intended use where the domain of the property is dpv:PersonDataHandling.

This gives two possible use cases of the terms: one is a very high level free use (no domain/range constraints) but at the same time a domain restricted usage depicted in the diagram. Which assumptions are assumed in which part of the text might be unclear.

If the intend is to allow the first as a good practice, then it might be good to highlight it.

For the rest this issue can be closed.

**Comment by coolharsh55** [comment]
Thanks for the help. I've made a note for when the diagram is updated to indicate the open-ness of domain/range.
