### ISSUE TITLE
OWL serialization of DPV and extensions

### ISSUE THREAD

**Issue by pab-github** [w3c/dpv#42]
Dear all, the reasoners for compliance checking expect the ontologies in owl format, which is related to Turtle and RDF but different.  It would be helpful to add the OWL serialization to the others already present in the repository.

Functionally, all supported syntax would do (Manchester, functional, XML), but Manchester is the closest to RDF and Turtle, so it may be a preferred choice, as it may look more familiar to RDF and Turtle users.

**Comment by coolharsh55** [comment]
Thanks Piero. I've added code support in 1a9bb10ace15480685875b2bf95bfe2c55533924 for exporting `.owl` files in Machester syntax (only) for DPV-OWL and extensions, e.g. see https://github.com/w3c/dpv/blob/master/dpv-owl/dpv.owl. I've created #43 to discuss additional axioms to be included within DPV-OWL - please also take a look there.

**Comment by coolharsh55** [comment]
@pab-github Hi, are there any followup points/actions for this discussion? 

If there are no more actions for this discussion, I will mark it as resolved on OCT-15.
