### ISSUE TITLE
dpv:Concept definition is missing in spec and serialisations

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dpv#51]
Hi,

in many properties this is mentioned but not defined/nor resolveable.

kr,

Bert

**Comment by coolharsh55** [comment]
Hi. Thanks for noticing and pointing this out. I will fix this in the next minor update, probably will be published tomorrow eve along with other fixes.

**Comment by coolharsh55** [comment]
@bertvannuffelen I've added HTML description for Concept in 4027fbd - you can see it live at https://harshp.com/dpv-x/dpv/#Concept Let me know if there is anything more to do here.
