### ISSUE TITLE
Clarify use of unspecified as property range

### ISSUE THREAD

**Issue by bertvannuffelen** [w3c/dpv#52]
The semantics of a domain or range that is _unspecified_ is unclear.
Either use rdf:Resource, or owl:Thing, or ANY or leave it blank. (Such technical broad ranges can be useful, e.g. if it is object property an xsd:date is probably not an acceptable value).
 
_Unspecified_ feels like the working group did not reach an agreement.  In W3C DCAT it is just left blank. no statement at all. Indicating that anybody can make any assumption of it. 

If you want to use the term, please add the semantics in the document.

kr,

Bert

**Comment by coolharsh55** [comment]
Hi. Yes, here unspecified means blank. The entry in the table is intended to explicitly denote this information i.e. that it was left blank. Let me know what's a better phrase to make this clear. If it would be better to phrase it as "left blank / unspecified" - I can make this change.
