### ISSUE TITLE
HumanResources is not a defined term

### ISSUE THREAD

**Issue by Zburator** [w3c/dpv#70]
HumanResouces is not defined as a term but it is used as a subType for PersonnelManagement.
https://w3id.org/dpv#HumanResources
https://w3id.org/dpv#PersonnelManagement
 

I see that there is a https://w3id.org/dpv#HumanResourceManagement , is this term supposed to be the upgraded version?

**Comment by coolharsh55** [comment]
> Hi there seems to be additional terms that are not defined: 
CrytographicMethods (https://w3c.github.io/dpv/dpv/#CrytographicMethods ) 

Typo, has been fixed as `CryptographicMethods`

> DataProcessingRecord (https://w3c.github.io/dpv/dpv/#DataProcessingRecord) 
> SecurityAssessment (https://w3c.github.io/dpv/dpv/#SecurityAssessment)

Typo, was plurals, fixed, as `DataProcessingRecord` and `SecurityAssessment`

I will upload the new versions tomorrow or Friday.
