### ISSUE TITLE
Broken link in 1.2 Base Vocabulary

### ISSUE THREAD

**Issue by derhagen** [w3c/dpv#72]
The first link "link" in the Table under [1.2 Base Vocabulary](https://w3c.github.io/dpv/dpv/#vocab-base) (column Relevant Section) is broken. Either replace by `[=hasPersonalData=]` (as consistent with the other rows) or add a `#`.

```
<tr>
<td><a data-link-type="dfn" href="#dfn-personaldata" class="internalDFN" id="ref-for-dfn-personaldata-3"><code>PersonalData<!---0.647581%--></code></a></td>
<td><a href="vocab-personaldata">link</a></td>
</tr>
```
Broken link in line 3.

**Comment by coolharsh55** [comment]
Hi. Thanks for the observations. I'm working on DPV today, and I'll integrate these. The changes may take a couple of days to reflect on the live version, as I'm also working on other fixes. If you find anything else in the mean time, please let us/me know.
