### ISSUE TITLE
SKOS version of DPV taxonomy

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#8]
| Migrated [ISSUE-14](https://www.w3.org/community/dpvcg/track/issues/14): We may want to add a non-normative comment in the spec that/how the taxonomy can be used as SKOS

State:    OPEN
Opened on:    2019-04-04

Related Emails:
1.  +[ISSUE-14: We may want to add a non-normative comment in the spec that/how the taxonomy can be used as skos.](https://www.w3.org/mid/E1hByAU-00029R-9U@asterion.w3.org) (from sysbot+tracker@w3.org on 2019-04-04)

Related Notes:
[axelpolleres]: we may refer to this link https://www.w3.org/2006/07/SWD/SKOS/skos-and-owl/master.html - 5 Apr 2019, 13:32:27

**Comment by coolharsh55** [comment]
The original issue was about adding a comment as to how the vocabulary could be used as/with SKOS. I've changed the heading to instead indicate creation of a SKOS version as the action going ahead. For benefit of interpretation and clarity, the SKOS version could have separate IRIs so as to not muddy the waters between SKOS and OWL concepts sharing the same IRIs, e.g. in reasoning.

**Comment by RinkeHoekstra** [comment]
There is no reason to differentiate SKOS and OWL names as OWL2 allows for punning between classes and instances.

IMO a SKOS vocabulary, or instances rather than classes, are more suited as modeling construct for such things as the personal data categories.

Could you give an example of what an instance of "Age" would look like?

How would I relate a dataset to that personal data category?

**Comment by coolharsh55** [comment]
Hi. I agree that OWL2 and SKOS can be compatible through punning, but this does not mean they should be provided within the same namespace. An adopter/user of OWL2 may not want SKOS declarations or vice-versa. Then there are implications between using instance and subclass and corresponding SKOS properties, which can get confusing and problematic. E.g. below both subclasses and instances can become `broader` relationships, of they can be retained by using both `skos:Concept` and `rdfs:Class`. 

```
ex:A rdfs:subClassOf ex:B .
ex:A skos:broader ex:B .

ex:M a ex:N .
ex:M skos:broader ex:N .
```

Then there is the question of how to provide taxonomies. In OWL2, the parent concept and subclasses form a tree, which is a taxonomy. In SKOS, the same can be done using narrower/broader, but also using Scheme or Collections. If using Schemes or Collections, this breaks the strict compatibility between OWL2 and SKOS concepts (e.g. member / top concept vs broader). Hence this open issue for discussion.

As for `Age`, I guess something like this:
```
ex:Age a skos:Concept ;
    skos:broader dpv:PersonalData .
ex:PDH a dpv:PersonalDataHandling ;
    dpv:hasPersonalData ex:Age .
```

But then if you want to specify 'instances' of `Age`, then you either need classes or additional SKOS concepts.
```
# using rdfs:Class
ex:Age a skos:Concept, rdfs:Class .
ex:MyAge a ex:Age ; rdf:value 99 .

# using skos:broader
ex:MyAge skos:broader ex:Age ; rdf:value 99 .
```

**Comment by coolharsh55** [comment]
DPV v0.4 is now an 'abstract' vocabulary or data model, with DPV-SKOS providing SKOS+RDFS and DPV-OWL providing OWL 2 serialisations with their respective semantics. This permits usage of DPV as convenient in an use-case. Note DPV itself is serialised using SKOS, so if someone wants a 'pure SKOS vocab', then DPV itself is sufficient. If you need SKOS concepts but also RDFS style classes, properties, instances, then DPV-SKOS is sufficient. If you need expressivity of OWL (e.g. subclass axioms) then DPV-OWL is there. If there are no further discussions on this, I will close the issue next week.
