### ISSUE TITLE
Add `CrossBorderTransfer` as a type of `Transfer` processing

### ISSUE THREAD

**Issue by coolharsh55** [w3c/dpv#88]
Cross border (data) transfers have a lot of obligations, requirements, and implications associated with them. While they can be detected with transfer and sender/recipient information, a quicker way to indicate cross border transfers are happening would be beneficial for keeping the information succint and directly relevant to real-world documentation. Additionally, they can be used to trigger validations, such as ensuring a sender and recipient location or jurisdiction is provided and is correct. Cross border definitions vary based on domain and jurisdiction, therefore the concept definition shouldonly specify "transfers where processing is carried out across different locations that cross jurisdictional borders". This allows the concept to be used for any type of 'border', e.g. city, province, nation, supra-national.

**Comment by smartopian** [comment]
in particular, there are 2 items to present for consideration
1. the use of services that are local but use cloud services - see [(Caspar.B-FISA)](https://www.youtube.com/watch?v=d7TyBK-gMgk)
2. wether there is transparency AKA. record of processing activity, and if (unilike cookies ) this is shared or controlled by the  PII Principal (or more accurately - under which governance policy does the processing present under ?)

**Comment by coolharsh55** [comment]
Hi. The concept `CrossBorderTransfer` here only refers to whether the `Transfer` of data is across borders (specifically relevant for Third Countries). Local to Cloud can include cross-border transfers. Transparency is not related to this concept (we have notices to represent that e.g. Transfer notice), and 'Control' by PII Principal has to be based on a legal basis for cross border transfers.

**Comment by coolharsh55** [comment]
> Isn’t a  notice is required of risks for transboarder data transfer?

Information can be provided via the data transfer notice - but we don't dictate what to provide in it [https://w3id.org/dpv#DataTransferNotice](http://localhost:8000/dpv/#DataTransferNotice)
