### ISSUE TITLE
dpv-gdpr:GDPRLawfulness typo 

### ISSUE THREAD

**Issue by aamedina** [w3c/dpv#95]
There is a broken reference in the GDPR vocabulary here:
https://github.com/w3c/dpv/blob/98280f63c41ac4b8c775c352250da466652ed895/dpv-gdpr/dpv-gdpr.ttl#LL953C31-L953C31

I believe it should be referencing dpv-gdpr:GDPRLawfulness 
https://github.com/w3c/dpv/blob/98280f63c41ac4b8c775c352250da466652ed895/dpv-gdpr/dpv-gdpr.ttl#L971

Let me know if I can help fix this. I was unsure how you are compiling the RDF output. What is the "root" of the ontology in your workflow that generates the files?

If it is https://github.com/w3c/dpv/blob/master/dpv-gdpr/modules/compliance.ttl then would patching this file be sufficient for a pull request? 

Thank you for your work on this vocabulary.

**Comment by coolharsh55** [comment]
Hi. Yes you are correct. Its a typo - the IRI should be `GDPRLawfulness`. I have changed it in the source CSVs, a copy of which will be stored here: https://github.com/w3c/dpv/blob/master/documentation-generator/vocab_csv/GDPR_compliance.csv the next time we update the concepts.

The file you have linked is the output produced from these CSVs (by converting to RDF). You don't need to do anything more - the changes will be reflected automatically when we next run the update which will pull the CSVs and generate the RDF. We have a new release coming this month, and I will leave the issue open to make sure this is fixed and credit you in the release notes. There are supposed to be tests that detect this as per #71 - so I will see what isn't working correctly. 

Let me know if you notice anything else, or want to help with any of the above or something else.

Thanks, Harsh
